export enum EstadoPaciente {
  ESPERANDO_DETERMINACION,
  SIENDO_DETERMINADO,
  ESPERANDO_AUTORIZACION,
  ESPERANDO_ATENCION,
  SIENDO_ATENDIDO,
  ESPERANDO_PAGO,
  PAGANDO,
  INTERRUMPIDO,
}
